export const mockDashboardLayout = [
    {
        id: 'widget8',
        type: 'chart',
        title: 'Sales Pipeline',
        cols: 3,
        rows: 2,
        x: 6,
        y: 1,
        content: {
            chartType: 'bar',
            dataSource: 'pipeline_stages',
            refreshInterval: 300000,
            data: [
                { name: 'Lead', value: 250000 },
                { name: 'Qualification', value: 180000 },
                { name: 'Proposal', value: 120000 },
                { name: 'Negotiation', value: 90000 },
                { name: 'Closed Won', value: 75000 },
            ],
        },
    },
    {
        id: 'widget9',
        type: 'chart',
        title: 'Product Category Performance',
        cols: 3,
        rows: 2,
        x: 0,
        y: 1,
        content: {
            chartType: 'bar',
            dataSource: 'product_categories',
            refreshInterval: 600000,
            data: [
                { name: 'Enterprise Solutions', value: 150000 },
                { name: 'Cloud Services', value: 120000 },
                { name: 'Consulting', value: 90000 },
                { name: 'Support', value: 60000 },
                { name: 'Training', value: 30000 },
            ],
        },
    },
    {
        id: 'widget10',
        type: 'chart',
        title: 'Sales Team Performance',
        cols: 3,
        rows: 2,
        x: 3,
        y: 1,
        content: {
            chartType: 'line',
            dataSource: 'team_performance',
            refreshInterval: 900000,
            data: [
                {
                    name: 'Team A',
                    series: [
                        { name: 'Q1', value: 120000 },
                        { name: 'Q2', value: 150000 },
                        { name: 'Q3', value: 180000 },
                        { name: 'Q4', value: 200000 },
                    ],
                },
                {
                    name: 'Team B',
                    series: [
                        { name: 'Q1', value: 100000 },
                        { name: 'Q2', value: 130000 },
                        { name: 'Q3', value: 160000 },
                        { name: 'Q4', value: 190000 },
                    ],
                },
            ],
        },
    },
    {
        id: 'widget11',
        type: 'metric',
        title: 'Deal Metrics',
        cols: 3,
        rows: 1,
        x: 0,
        y: 0,
        content: {
            chartType: 'metric',
            metrics: ['closureRate', 'avgDealSize', 'dealVelocity'],
            data: { closureRate: 65, avgDealSize: 45000, dealVelocity: 28 },
        },
    },
    {
        id: 'widget12',
        type: 'chart',
        title: 'Average Deal Size Trend',
        cols: 4,
        rows: 2,
        x: 8,
        y: 3,
        content: {
            chartType: 'line',
            dataSource: 'deal_size_trend',
            refreshInterval: 1200000,
            data: [
                {
                    name: 'Deal Size',
                    series: [
                        { name: 'Jan', value: 42000 },
                        { name: 'Feb', value: 44000 },
                        { name: 'Mar', value: 47000 },
                        { name: 'Apr', value: 45000 },
                        { name: 'May', value: 50000 },
                    ],
                },
            ],
        },
    },
    {
        id: 'widget13',
        type: 'chart',
        title: 'Revenue Distribution',
        cols: 4,
        rows: 2,
        x: 0,
        y: 3,
        content: {
            chartType: 'pie',
            dataSource: 'revenue_distribution',
            refreshInterval: 1500000,
            data: [
                { name: 'New Business', value: 450000 },
                { name: 'Recurring Revenue', value: 650000 },
                { name: 'Upsells', value: 200000 },
            ],
        },
    },
    {
        id: 'widget1',
        type: 'chart',
        title: 'Monthly Revenue',
        cols: 4,
        rows: 2,
        x: 4,
        y: 3,
        content: {
            chartType: 'line',
            dataSource: 'revenue_metrics',
            refreshInterval: 300000,
            data: [
                {
                    name: 'Revenue',
                    series: [
                        { name: 'January', value: 50000 },
                        { name: 'February', value: 60000 },
                        { name: 'March', value: 70000 },
                        { name: 'April', value: 80000 },
                        { name: 'May', value: 90000 },
                    ],
                },
            ],
        },
    },
    {
        id: 'widget2',
        type: 'metric',
        title: 'Profit Goals',
        cols: 3,
        rows: 1,
        x: 3,
        y: 0,
        content: {
            chartType: 'metric',
            metrics: ['goal', 'achieved', 'remaining'],
            data: { goal: 100000, achieved: 75000, remaining: 25000 },
        },
    },
    {
        id: 'widget3',
        type: 'chart',
        title: 'Top Accounts by Revenue',
        cols: 4,
        rows: 3,
        x: 6,
        y: 5,
        content: {
            chartType: 'bar',
            dataSource: 'top_accounts',
            refreshInterval: 600000,
            data: [
                { name: 'Account A', value: 30000 },
                { name: 'Account B', value: 25000 },
                { name: 'Account C', value: 20000 },
                { name: 'Account D', value: 15000 },
                { name: 'Account E', value: 10000 },
            ],
        },
    },
    {
        id: 'widget4',
        type: 'metric',
        title: 'Sales Conversion Rate',
        cols: 3,
        rows: 1,
        x: 6,
        y: 0,
        content: {
            chartType: 'metric',
            metrics: ['leads', 'conversions', 'conversionRate'],
            data: { leads: 200, conversions: 50, conversionRate: 25 },
        },
    },
    {
        id: 'widget5',
        type: 'chart',
        title: 'Quarterly Profit',
        cols: 3,
        rows: 2,
        x: 9,
        y: 1,
        content: {
            chartType: 'pie',
            dataSource: 'quarterly_profit',
            refreshInterval: 900000,
            data: [
                { name: 'Q1', value: 20000 },
                { name: 'Q2', value: 30000 },
                { name: 'Q3', value: 25000 },
                { name: 'Q4', value: 35000 },
            ],
        },
    },
    {
        id: 'widget6',
        type: 'metric',
        title: 'Customer Satisfaction',
        cols: 3,
        rows: 1,
        x: 9,
        y: 0,
        content: {
            chartType: 'metric',
            metrics: ['satisfied', 'neutral', 'dissatisfied'],
            data: { satisfied: 80, neutral: 15, dissatisfied: 5 },
        },
    },
    {
        id: 'widget7',
        type: 'chart',
        title: 'Sales by Region',
        cols: 6,
        rows: 3,
        x: 0,
        y: 5,
        content: {
            chartType: 'gauge',
            dataSource: 'regional_sales',
            refreshInterval: 1800000,
            data: [
                { name: 'North', value: 30000 },
                { name: 'South', value: 40000 },
                { name: 'East', value: 35000 },
                { name: 'West', value: 45000 },
            ],
        },
    },
];
